apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'django'
        static_configs:
          - targets: ['faucet-web:8000']

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager:9093'

    rule_files:
      - '/etc/prometheus/alerts/*.yml'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  labels:
    app: prometheus
data:
  alerts.yml: |
    groups:
      - name: example-alerts
        rules:
          - alert: DjangoAppDown
            expr: up{job="django"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Django app is down"
              description: "The Django application has been down for more than 1 minute."
