# Generated by Django 5.1.4 on 2024-12-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('ip_address', models.GenericIPAddressField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed'), (4, 'Error')], default=1)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
